---
title: "Chapter 4 Notes"
author: "Kimaya Lacey"
format: docx
editor: visual
---

# Chapter 4 Notes

```{r}
library(tidyverse)
library(gapminder)
```

## 
```{r}
design_data <- gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarize(
    mean_life_expectancy = mean(
      lifeExp,
      na.rm = TRUE
    ),
    .groups = "drop"
  )
```


## 
```{r}
ggplot(
  data = gapminder %>%
    filter(year == 2007),
  mapping = aes(
    x = gdpPercap,
    y = lifeExp,
    color = continent
  )
) +
  geom_point(
    size = 3,
    alpha = 0.8
  ) +
  scale_x_log10() +
  scale_color_viridis_d() +
  labs(
    title = "Life Expectancy and GDP per Capita",
    x = "GDP per capita",
    y = "Life expectancy in years",
    color = "Continent"
  ) +
  theme_minimal()
```

## 
```{r}
ggplot(
  data = gapminder %>%
    filter(year == 2007),
  mapping = aes(
    x = gdpPercap,
    y = lifeExp,
    color = continent,
    shape = continent
  )
) +
  geom_point(
    size = 3,
    alpha = 0.8
  ) +
  scale_x_log10() +
  scale_color_viridis_d() +
  labs(
    title = "Life Expectancy and GDP per Capita",
    x = "GDP per capita",
    y = "Life expectancy in years",
    color = "Continent",
    shape = "Continent"
  ) +
  theme_minimal()
```

## 
```{r}
redesign_data <- gapminder %>%
  filter(
    year == 2007,
    continent %in% c(
      "Africa",
      "Americas",
      "Asia",
      "Europe"
    )
  ) %>%
  group_by(continent) %>%
  summarize(
    mean_life_expectancy = mean(
      lifeExp,
      na.rm = TRUE
    ),
    .groups = "drop"
  )
```


## 
```{r}
ggplot(
  data = redesign_data,
  mapping = aes(
    x = continent,
    y = mean_life_expectancy,
    fill = continent
  )
) +
  geom_col() +
  labs(
    title = "Life Expectancy",
    x = "Continent",
    y = "Mean"
  ) +
  theme_gray()
```


